# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gibbs_cpp <- function(N, thin) {
    .Call(`_gibbs_gibbs_cpp`, N, thin)
}

rcpp_hello_world <- function() {
    .Call(`_gibbs_rcpp_hello_world`)
}

